# ğŸ” Hugging Face Configuration
LLM_MODEL = "moonshotai/Kimi-K2-Instruct"
HUGGINGFACE_API_KEY = ""

# ğŸ” Gemini Configuration
GEMINI_API_KEY = "AIzaSyCLZphmq2tR-dRbewXucU63SL5r8Wo0uWk"
GEMINI_MODEL_NAME = ""  # or "models/gemini-1.5-pro"

# ğŸ” NVIDIA Configuration
NVIDIA_API_KEY = ""

# ğŸ“ Document Paths
DOCS_FOLDER = "Data/Docs"
CHECKLIST_PDF = "Data/Checklist/chkList.pdf"
OUTPUT_DIR = "output"

# ğŸ§  Vector Store & Chunking Settings
VECTOR_DB_PATH = "./vector_db"
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
